-- Flyway Migration: Create Database Schema from Entity Models
-- Description: Creates tables for Movie and Genre entities with their relationships
-- Generated from: Genre.java and Movie.java entity models
-- Author: Generated based on JPA entity annotations
-- Date: 03/11/2025

-- Create Genre table
CREATE TABLE IF NOT EXISTS genre (
                                     id INTEGER NOT NULL,
                                     title VARCHAR(255),
    CONSTRAINT pk_genre PRIMARY KEY (id)
    );

-- Create Movie table
CREATE TABLE IF NOT EXISTS movie (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                                     title VARCHAR(255) NOT NULL,
    sinopsis VARCHAR(255) NOT NULL,
    premiere_date DATE NOT NULL,
    youtube_trailer_id VARCHAR(255) NOT NULL,
    route_cover VARCHAR(255),
    CONSTRAINT pk_movie PRIMARY KEY (id)
    );

-- Create junction table for Many-to-Many relationship between Movie and Genre
CREATE TABLE IF NOT EXISTS genre_movie (
                                           movie_id INTEGER NOT NULL,
                                           id_genre INTEGER NOT NULL,
                                           CONSTRAINT fk_genre_movie_movie FOREIGN KEY (movie_id) REFERENCES movie(id) ON DELETE CASCADE,
    CONSTRAINT fk_genre_movie_genre FOREIGN KEY (id_genre) REFERENCES genre(id) ON DELETE CASCADE
    );

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_genre_movie_movie_id ON genre_movie(movie_id);
CREATE INDEX IF NOT EXISTS idx_genre_movie_genre_id ON genre_movie(id_genre);
CREATE INDEX IF NOT EXISTS idx_movie_title ON movie(title);
CREATE INDEX IF NOT EXISTS idx_movie_premiere_date ON movie(premiere_date);

-- Comments for documentation
COMMENT ON TABLE genre IS 'Stores movie genre categories';
COMMENT ON TABLE movie IS 'Stores movie information including title, synopsis, premiere date, and trailer details';
COMMENT ON TABLE genre_movie IS 'Junction table for many-to-many relationship between movies and genres';
COMMENT ON COLUMN movie.id IS 'Auto-generated primary key';
COMMENT ON COLUMN movie.title IS 'Movie title (required)';
COMMENT ON COLUMN movie.sinopsis IS 'Movie synopsis/description (required)';
COMMENT ON COLUMN movie.premiere_date IS 'Movie premiere/release date (required)';
COMMENT ON COLUMN movie.youtube_trailer_id IS 'YouTube video ID for the movie trailer (required)';
COMMENT ON COLUMN movie.route_cover IS 'Path or URL to the movie cover image (optional)';
