-- Flyway Migration: Database Schema from Entity Models
-- Description: Creates database schema based on Genre and Movie JPA entities
-- Database: PostgreSQL
-- Spring Boot Version: 3.5.7
-- Entities: Genre.java, Movie.java
-- Date: 03/11/2025
-- Author: Generated from JPA Entity Models
-- Note: This migration is idempotent and safe to run on existing databases

-- ============================================================================
-- Table: genre
-- Entity: id.my.hendisantika.movietrailer.entity.Genre
-- Description: Stores movie genre categories
-- ============================================================================
CREATE TABLE IF NOT EXISTS genre (
    id INTEGER NOT NULL,
    title VARCHAR(255),
    CONSTRAINT pk_genre PRIMARY KEY (id)
);

-- ============================================================================
-- Table: movie
-- Entity: id.my.hendisantika.movietrailer.entity.Movie
-- Description: Stores movie information with title, synopsis, premiere date, and trailer
-- ============================================================================
CREATE TABLE IF NOT EXISTS movie (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    sinopsis VARCHAR(255) NOT NULL,
    premiere_date DATE NOT NULL,
    youtube_trailer_id VARCHAR(255) NOT NULL,
    route_cover VARCHAR(255),
    CONSTRAINT pk_movie PRIMARY KEY (id)
);

-- ============================================================================
-- Junction Table: genre_movie
-- Relationship: Movie.genres (ManyToMany) <-> Genre
-- Description: Many-to-Many relationship between movies and genres
-- JoinTable annotation: name="genre_movie", joinColumns="movie_id", inverseJoinColumns="id_genre"
-- ============================================================================
CREATE TABLE IF NOT EXISTS genre_movie (
    movie_id INTEGER NOT NULL,
    id_genre INTEGER NOT NULL,
    CONSTRAINT fk_genre_movie_movie FOREIGN KEY (movie_id)
        REFERENCES movie(id) ON DELETE CASCADE,
    CONSTRAINT fk_genre_movie_genre FOREIGN KEY (id_genre)
        REFERENCES genre(id) ON DELETE CASCADE
);

-- ============================================================================
-- Indexes for Performance Optimization
-- ============================================================================
-- Index for foreign key lookups
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_genre_movie_movie_id') THEN
        CREATE INDEX idx_genre_movie_movie_id ON genre_movie(movie_id);
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_genre_movie_genre_id') THEN
        CREATE INDEX idx_genre_movie_genre_id ON genre_movie(id_genre);
    END IF;
END
$$;

-- Index for movie title searches
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_movie_title') THEN
        CREATE INDEX idx_movie_title ON movie(title);
    END IF;
END
$$;

-- Index for premiere date queries
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_movie_premiere_date') THEN
        CREATE INDEX idx_movie_premiere_date ON movie(premiere_date);
    END IF;
END
$$;

-- ============================================================================
-- Field Mapping Documentation
-- ============================================================================
-- Genre Entity Mapping:
--   - id (Integer, @Id): genre.id
--   - title (String): genre.title
--
-- Movie Entity Mapping:
--   - id (Integer, @Id, @GeneratedValue(strategy=IDENTITY)): movie.id
--   - title (String, @NotBlank): movie.title (NOT NULL)
--   - sinopsis (String, @NotBlank): movie.sinopsis (NOT NULL)
--   - premiereDate (LocalDate, @NotNull, @DateTimeFormat): movie.premiere_date (NOT NULL)
--   - youtubeTrailerId (String, @NotBlank): movie.youtube_trailer_id (NOT NULL)
--   - routeCover (String): movie.route_cover (nullable)
--   - genres (List<Genre>, @ManyToMany, @NotEmpty): genre_movie junction table
--   - frontPage (MultipartFile, @Transient): NOT persisted to database
--
-- Hibernate Naming Strategy (Spring Boot Default):
--   - camelCase -> snake_case: premiereDate -> premiere_date, youtubeTrailerId -> youtube_trailer_id
--   - Entity name -> lowercase table name: Genre -> genre, Movie -> movie
